# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 498d3887286acd259a3bd185869bdc7e7b171a5f0d3fd4c33899c246add568117af6a9f93c6a2b600f00c307e4eaed50d6dde739cac65d4cce939bd861c45bdd

test:
  secret_key_base: 9bb3d5c75b8cd1d8f304d1f72fbf03888315f47b310533ac7b625a0f211eeb38cde1bec41b05fc99c152e9a757a91feafeb8df9b88128745d81faee13dac7e78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
